"""
Domain models, enums, and dataclasses for Fleksa.
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
import numpy as np


class BessMode(str, Enum):
    CHARGE = "CHARGE"
    DISCHARGE = "DISCHARGE"
    HOLD = "HOLD"


class SystemDirection(str, Enum):
    ENERGY_DEFICIT = "ENERGY_DEFICIT"
    ENERGY_SURPLUS = "ENERGY_SURPLUS"
    BALANCED = "BALANCED"


class LoadClass(int, Enum):
    CLASS_0_CRITICAL = 0      # Non-interruptible, zero latency tolerance
    CLASS_1_DEFERRABLE = 1    # Batch embedding/ETL, shiftable 1-8h
    CLASS_2_PREEMPTIBLE = 2   # Pre-train / LoRA, checkpoint & pause
    CLASS_3_THROTTLABLE = 3   # DVFS power-cappable inference / analytics


@dataclass
class FacilityState:
    """Represents the instantaneous physical state of a consumer/BESS facility."""
    bess_soc_kwh: float
    bess_capacity_kwh: float = 500.0
    bess_max_kw: float = 250.0
    min_soc_pct: float = 0.15
    max_soc_pct: float = 0.95
    eta_rt: float = 0.88  # Round-trip efficiency
    indoor_temp_c: float = 22.0
    queue_backlog: float = 0.0  # FLOPS / jobs queued
    cell_temperature_c: float = 25.0
    state_of_health: float = 1.0  # 1.0 = 100% health


@dataclass
class MarketDataHorizon:
    """24-hour or multi-step market price and environmental telemetry horizon."""
    hours: int
    ptf_try_kwh: np.ndarray        # Day-Ahead price in TL/kWh
    base_load_kw: np.ndarray       # Baseline facility load
    pv_gen_kw: np.ndarray          # Solar generation forecast
    ambient_temp_c: np.ndarray     # Outdoor ambient temperature
    smf_try_kwh: Optional[np.ndarray] = None  # Balancing market price


@dataclass
class OptimizationResult:
    """Output plan generated by the MPC MILP solver."""
    status: str
    projected_cost_try: float
    p_ch_kw: List[float]
    p_dis_kw: List[float]
    p_grid_kw: List[float]
    gpu_power_cap_pct: List[float]
    soc_trajectory_kwh: List[float]
    expected_savings_try: float
    metadata: Dict[str, Any] = field(default_factory=dict)
